services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    ports: 
      - "127.0.0.1:5432:5432"
    volumes:
      - type: volume
        source: cafe-db
        target: /var/lib/postgresql/data
  website:
    build:
      context: .
      target: cafe_website
    restart: always
    ports:
      - "443:443"
    env_file: .env
    environment:
      DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"
      CARGO_MANIFEST_DIR: "/"
    configs:
      - source: web_config
        target: /var/cafe_website/config.toml

configs:
  web_config:
    file: ./docker.config.toml
    

volumes: 
  cafe-db:
    
